### ISSUE TITLE
Question: force Bermuda to create a device for an elusive MAC address that is not yet "seen" by home assistant?

### ISSUE THREAD

**Issue by Ocramius** [agittins/bermuda#124]
I've avoided the template since this is a question, rather than a bug report: this is probably me needing a direction and/or documentation, rather than something needing fixing in Bermuda itself.

I'm currently trying to configure a new device under `https://my-home-assistant/config/integrations/integration/bermuda`, and the entry mask that has the `placeholder="List of Bluetooth devices to specifically create tracking entities for."` is only allowing selection of MAC addresses that it has already "seen".

I'm wondering if:

 * it is possible to enter MAC address that HA Bluetooth has **not yet** seen (effectively skipping the UI validation)
 * I'm doing something wrong while trying to get HA to see some of my devices

## Further context

 * I'm trying to pair my Pixel 5 phone, and I understand that phones are tricky / fiddly due to potential MAC randomization.
 * I have a very noisy environment due to many Philips Hue devices using BLE themselves

My the phone is not being picked up by passive scanning: it is pairable from my main work computer, so I managed to extract its BT MAC address via `bluetoothctl paired-devices` there.

I was wondering if I could just take that MAC address and ask Bermuda to create a device from it, or if that's nonsensical because Bermuda **must** first have seen the device, for some reason.

**Comment by Ocramius** [comment]
I guess this is a general question on how to force devices to appear in HA :D  

Also: is that list that I'm seeing somehow limited? Because I have at least 70~80 Bluetooth-capable devices around me, so I'm wondering if HA is somehow limiting what's visible.

**Comment by agittins** [comment]
The issue template is helpful regardless because it lets me know what version of the code you are using, and what your settings are, for instance. Having it filled out is never unhelpful, and is usually important.

If Bermuda can't "see" the address, then adding it to the config anyway won't fix it, because it still won't "see" any advertisements. In the case of a pixel, this is because it never sends adverts with that address, so there's no point trying harder to listen for them, they'll never arrive.

I'd suggest running the HA companion app on your pixel, and configuring it to send iBeacon adverts. These will be sent with randomised MAC addresses, and the *next* release of Bermuda includes the feature of being able to track iBeacons, so that should solve the issue for you.

I'm hoping to get that new version released "soon" - hopefully in the next several days.

**Comment by Ocramius** [comment]
Awesome! That's the piece of info I was missing: beacons of mobile phones (via companion app) aren't yet picked up be Bermuda!

Thanks for that! 😁

Closing here, as the missing puzzle piece is provided, thanks! 💪

**Comment by agittins** [comment]
Hey @Ocramius you might like to try out the new version v0.5.0 I just released - it includes support for the Android HA Companion app's iBeacon 💥

**Comment by Ocramius** [comment]
Gave it a shot locally: no luck, although I just enabled the iBeacon integration

**Comment by agittins** [comment]
Hmm that's very odd! It should work really easily out of the box - personally I haven't enjoyed the way the native `iBeacon` integration works, but if it's doing what you need that's great.

Which bluetooth proxies are you using - esphome or Shelly Plus?

If you want to dig further let me know, happy to help work out what's going on. We'll need to start with a screenshot of your bermuda config dialog, and the first page or so of output from the `dump_devices` service call.

**Comment by Ocramius** [comment]
> Hmm that's very odd! It should work really easily out of the box - personally I haven't enjoyed the way the native iBeacon integration works, but if it's doing what you need that's great.

@agittins I'd first check any logs about the integrations on my end: it's probably broken on my end :)
Probably getting to it this week :muscle: 

 > Which bluetooth proxies are you using - esphome or Shelly **Plus?

I'm currently trying on a `TP-Link UB500`, which is listed on the [docs](https://www.home-assistant.io/integrations/bluetooth) as problematic due to:

 > tp-link UB500 (RTL8761BU) - Frequent connection failures with active connections

Oh well, it's also apparently the most stable Linux Bluetooth USB adapter since a while. I forward the USB device from a  proxmox host down to the Home Assistant VM.

I have 2 * Shelly PRO 4 PM where Bluetooth proxy (passive scanning) is enabled, but I don't use them to test: I literally just sit near my server and try stuff out :-D

> If you want to dig further let me know, happy to help work out what's going on. We'll need to start with a screenshot of your bermuda config dialog, and the first page or so of output from the `dump_devices` service call.

Would it be OK with an anonymized version with MAC addresses snipped out?

**Comment by agittins** [comment]
Cool, all good! Whenever you get a chance :-)

USB bluetooth adaptors aren't terribly well-tested with Bermuda because my focus has been on getting Area-based distance ranging. That said, the device_tracker entity has been working well with local bluetooth for quite a while, so it *should* work.

I just pushed a release fixing a bug where local bluetooth dongles would "stick" to a device that had gone out of range, but I don't think this will have been affecting you.

FWIW, I also forward my usb adaptor via libvirt, which is the same backend that proxmox uses IIRC.

Redacted MACs is fine, it might be helpful if you can leave the first octet in place just for picking between different entries but it'll be fine either way. You're also welcome to PM things to me if you'd rather not share it with the entire planet. ash@ajg.net.au

The `dump_devices` output will tend to be rather huge, so you can just include the first page or two for starters, or specify the particular addresses you're interested in to cull down the results it gives (just hit the "fill example data" button for tips).

The proxies are really where it's at, in my opinion. Being able to receive BT data into your system from anywhere in the house, via redundant receivers, its just awesome. I like it better than zigbee/zwave because I'm not reliant on a single receiver for the entire network (of course it's not for everything). Anyway, I'm rambling again 🤣

**Comment by Ocramius** [comment]
> The `dump_devices` output will tend to be rather huge, so you can just include the first page or two for starters, or specify the particular addresses you're interested in to cull down the results it gives (just hit the "fill example data" button for tips). 

I noticed: I keep daily notes, and my notes repository grew substantially, that day (including debug logs of the integration :P ).

 > The proxies are really where it's at, in my opinion.

I've yet to try setting near one of the shellys while debugging: will try working close to the Bluetooth proxies next :-) 

 > I like it better than zigbee/zwave because I'm not reliant on a single receiver for the entire network (of course it's not for everything).

Mesh, yo. Honestly, I just want 802.11ah halow, and forever forget about Bluetooth/Zigbee/Thread/LoRa: just connect your ESP32-XYZ to my WiFi over WPA3, and enjoy IoT hell almost a kilometer away, in your little isolated VLAN :D

**Comment by Ocramius** [comment]
Just some feedback here: HA started picking up information about iBeacon through Bluetooth proxies, although with a ton of information being messy/missing:

![Selection_724](https://github.com/agittins/bermuda/assets/154256/1f11ba03-9048-4d5e-a2ff-3e0177bcc400)

The detection area kinda works too:
![Selection_725](https://github.com/agittins/bermuda/assets/154256/fcdb5bfe-7f16-43be-b9e9-17dc5b1ca43e)

Distance also kinda works, but needs better calibration: would probably need to understand calibration a bit better.

In the following screenshot, for reference, my phone has been ~2m away from a Shelly 1PM Mini Gen3 for a couple hours: 

![Selection_726](https://github.com/agittins/bermuda/assets/154256/af7de43d-bd19-4599-9fe9-ffa79ecbf148)

I'll keep things monitored, but Bluetooth proxy was indeed the way to go, and I'll now start setting up hidden Shelly switches everywhere to see if room detection works (as you can see, I currently only have 4 Bluetooth proxies)

**Comment by agittins** [comment]
Hey, sorry I missed your previous updates. It looks like things are working OK for you. The "missing" sensor entries there are actually just "disabled". By default we only enable the distance and area sensors, since that will provide the information most people require.

But for testing or other work, Bermuda also provides those "distance to.." and unfiltered sensors so that people can dig deeper into how it works internally. But we "disable" those sensors by default so that they don't clutter up dashboards and also so that they don't cause a lot of database size increase, as HA will start recording their history if they are enabled.

Calibration can be done by the steps in the readme - but it doesn't matter too much if you are just doing room-based detection, since everything is relative.
