### ISSUE TITLE
Merged Bermuda / PrivateBLE device pages are confusing, especially duplicated entity names

### ISSUE THREAD

**Issue by jaymunro** [agittins/bermuda#144]
## Version of the custom_component

0.6.1

## Describe the bug

After upgrading, the PrivateBLE devices are picked up beautifully. Nice job on finding this method to bring in IRK devices.

However, once the PrivateBLE entities are picked up, all the PrivateBLE entities seem to belong to Bermuda and there is no way to enter the PrivateBLE device (clicking on an entity inside PrivateBLE takes you to the Bermuda device). This may not be such an issue as all entities seem configurable except for:
- Renaming the device renames all Bermuda and PrivateBLE entities
- There are now two device_tracker entities named exactly the same, just the ID of the Bermuda one has `_2` on the end. This is confusing for writing automations, etc.

I think ideal would be for the entities to remain in their own integrations if this would work. If not easy, then maybe just adding the word "Bermuda" to the name and ID of the newly created entities. As it is it seems they all get created with the name and id of the PrivateBLE device.

<img width="1029" alt="Screenshot 2024-03-27 at 3 39 19 PM" src="https://github.com/agittins/bermuda/assets/1166024/e342f1d9-6351-420d-89a6-137a68e15f6f">

I also have a suggestion to mitigate the jumping between rooms we see in the screenshot. I'll add that to #134.

**Comment by agittins** [comment]
Great feedback, thanks!

Combining entities into devices from other integrations was a feature request, and I think it's a reasonable one - but as you note, it is rather confusing in this instance. It's useful in others, like the nmap tracker, or BTHome and other passive BLE integrations. I think it aids discovery - as long as names don't collide :-)

Especially the device tracker entity - I noticed that near release and wasn't sure if I should deliberately name mine differently or not - I decided not to based on the likelihood that people already have automations set up, so changing the default entity ids might break those - but I think I was wrong on that count - firstly because I suspect the entity id and name will persist if it already existed (ie, not be changed by the update) and secondly as you noted, it's bloody confusing - it's been bugging me already!

I think I'll change the default entity_id and name for the device trackers I create.

It's not well-explained in the docs, but my understanding is that "devices" are not owned by integrations, rather "entities" are per-integration, and a "device" is meant to collate entities from various integrations for a given "physical device". In that spirit, I would prefer to keep the grouping as-is, but I do need to address the confusing naming. (oh, and the fact that Bermuda's logo gets put in the top-right corner but Private_ble's doesn't I suspect is perhaps a missing setting / property in that integration, rather than a sign of "ownership".

**Comment by jaymunro** [comment]
I think that's the gist of it. If a user is wanting to report a bug in PrivateBLE, they still can I think. It's just the swapping from one integration to another when going through integrations > PrivateBLE > Device > (and then ending up in Bermuda)

Just the device_tracker is the main conflict.

If it's any easier to think about, there should be no conflicts with automations, templates, and such as the device_tracker. name does not change with the PrivateBLE entity. The Bermuda entity is new and so is not part of anything existing, nor should it be.

**Comment by agittins** [comment]
Yeah, I think the logo in the top-right corner is confusing, but on the top-left it's pretty clear that this device shows data from multiple integrations.

![image](https://github.com/agittins/bermuda/assets/752405/06046a06-0a0d-41cc-bf7c-384a8b8acf61)
![image](https://github.com/agittins/bermuda/assets/752405/4923f443-e003-4727-b468-a3d6747b9382)
![image](https://github.com/agittins/bermuda/assets/752405/839271ff-a04e-4f5e-ab5b-f9fcff18b1a8)

I'm not sure if there's a reason why one integration gets "featured" in the top-right over another.

But yes, I'll sort out the id's and name's to be more clear.
