### ISSUE TITLE
Small bug in logging missing area

### ISSUE THREAD

**Issue by hnykda** [agittins/bermuda#162]
Hey. Great project! 

This is just a small bug report. Bermuda told me in logs to assign area for one of my proxies. I did that, and it clearly works as I can see that devices are marked with that area. But on every reload of integration, I still see the log about missing area for my proxy:

Area assigned to the device:
![image](https://github.com/agittins/bermuda/assets/2741256/852156c0-3cf5-4a92-b1b5-4d27935be415)

Log:
![image](https://github.com/agittins/bermuda/assets/2741256/0e48769e-33d1-4edc-81c5-296001dfe625)

I restarted HA, reload Bermuda several times, but I still see the message about missing area in the logs.

Totally different thing, this sentence with scissors reads funny:
![image](https://github.com/agittins/bermuda/assets/2741256/cb6f277e-8fcd-4169-9c43-20edfe64f9f0)

I mean, sure, scissors can naturally increase humans walking speed twice as much - maybe my English comprehension is just bad though 😄 !

**Comment by agittins** [comment]
Ahh, well spotted! I suspect it's happening because I store "skeletons" of the proxy entries into Bermuda's configuration so that it will have some proxy data to work with at start up even if those particular proxies haven't reported in yet. I'm probably not refreshing the location id in the stored config after it changes, so for those first few seconds after a reload it's seeing stale data from the first time it saved it, before adding the area.

I'll dig into it and should have a fix soon - thanks for the concise report!

Hehe yeah the scissors bit is a joke - in Australia at least, "running with scissors" is a common idiom about safety and kids ignoring parental/teacher advice. I extrapolated that to infer that humans holding scissors can be assumed to have a higher average velocity than those without. It's a bit like having a "banana, for scale" in an image, I guess ;-)

One could also take it as an artistic statement about the folly of taking a measurement made by an inherently unreliable method (RF signal strength), and codifying strict rules to apply bounds to the movements of inherently unpredictable beings.

But mostly it's just a dumb joke! 😅

**Comment by agittins** [comment]
This should be fixed in the `main` branch now, and will be included in the next release (expected to be v0.6.4).

Thanks again for the report!

**Comment by hnykda** [comment]
> Hehe yeah the scissors bit is a joke [...]

I love it 😆
