### ISSUE TITLE
Readme - Adding to HACS custom repo step under What You Need

### ISSUE THREAD

**Issue by rendyhd** [agittins/bermuda#213]
Hi,
I am still determining if this is an issue or by design since the [Installation instructions](https://github.com/agittins/bermuda?tab=readme-ov-file#installation) are clear and work.
However, as on the top of the page, the big blue buttons (OPEN HACS REPOSITORY) you see twice don't work without adding the custom repo manually; I would personally add that step as part of the pullet points under [What you need](https://github.com/agittins/bermuda?tab=readme-ov-file#what-you-need) for simplicity and clarity.

Thanks for the work!

**Comment by agittins** [comment]
Oh, thanks! Not by design, but via the bountiful rivers of ignorance! 🤣 

I thought it managed the adding of the repo as well, but I didn't test it properly (given the repo's already in my HACS). I am sure I've seen cases where those links do manage that, so I'll see if I can work it out - I was somewhat sleep-deprived when I added the buttons, I might have missed something simple.

Thanks for the heads-up!

**Comment by agittins** [comment]
Turns out I didn't set the `category` field correctly on the link. It should now work to add the repo, and if it's already added it will show the integration's page.

It seems to work here, but feel free to re-open if it's not acting as expected, or if the readme needs more clarification for new users. Thanks again for the report.
