### ISSUE TITLE
Support for tracking kindle (paperwhites)

### ISSUE THREAD

**Issue by jonlove234** [agittins/bermuda#233]
**Is your feature request related to a problem? Please describe.**
Kindle Paperwhites support bluetooth, and can connect (only) to audio servers. There is no native "find my" type functionality.

**Describe the solution you'd like**
A way to identify the IRK/pair with a Kindle Paperwhite to be able to use it in bermuda triangulation.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by agittins** [comment]
Bermuda tracks BLE advertisements.

If the paperwhite sends BLE adverts, we might be able to identify them and track them. If it does not send adverts, then there's nothing we can do. Actually, if the paperwhite is sending adverts, it should already appear in Bermuda's list of possible devices you can add.

If you install an app like NRFConnect on your phone, you should be able to see if the paperwhite is sending any adverts - take some screenshots of the data it's sending and pop them in here, I can see what can be done.
You might see *lots* of bluetooth devices in the app, place the phone and paperwhite right next to each other while scanning, and the paperwhite should be the one with the "smallest" (ie, least-negative) RSSI value (so like, -27 or something, not -80).

I don't hold out much hope, but this is the best way of finding out what might be possible.

**Comment by jonlove234** [comment]
(Also, thanks Ashley for the great tool. I'm finding it very useful for tracking Apple devices!)

Sadly it doesn't look like it appears. Even with the Kindle literally next to my phone, very few devices that it found has an RSSI greater than (well, lower negative) number 😣 I played around with filtering to include A/G devices just in case, but no luck still - but that's why there are more devices on some screenshots.

![Screenshot_20240708-154006](https://github.com/agittins/bermuda/assets/123476466/793f9bc5-384c-4d36-b466-069fcc6e8d4b)
![Screenshot_20240708-154012](https://github.com/agittins/bermuda/assets/123476466/c24d1d25-bac4-42a7-81e4-43129a99b924)
![Screenshot_20240708-154210](https://github.com/agittins/bermuda/assets/123476466/8e5d45c1-a246-453d-b877-a5fc771401a7)
![Screenshot_20240708-154232](https://github.com/agittins/bermuda/assets/123476466/bfb0dc6c-0a8d-444e-9e81-224576878d67)

**Comment by agittins** [comment]
:( Yeah, it does not look promising. I suspect that the kindle just isn't sending any broadcasts. From the bit of googling I have done on them, it looks like Amazon have the bluetooth pretty tightly constrained in what it can do (with geolocking the bluetooth feature depending on whether audible is available in that region etc), so I doubt there'll be any way to alter the bluetooth behaviour other than hacking the device in some way.

That's a real shame (although good from a privacy aspect, I guess). I think the only (reasonable) option might be to attach a tracking tile to it in some way.

I'll close this since I don't think there's anything I can offer for this device, but feel free to re-open if anything else comes to light.
