### ISSUE TITLE
Exclude bleutooth tracker

### ISSUE THREAD

**Issue by Sceptorrh** [agittins/bermuda#256]
**Is your feature request related to a problem? Please describe.**
I have a strong bluetooth tracker in a central location of my home, This is used to track all of my plant sensors around the house.
Apart from that I have some shelly plugs in different rooms that could be used for room detection.
Sadly my central trackers signal is most the time stronger than the shelly's so I am unable to use the room detection.

**Describe the solution you'd like**
I would love an option to exclude the central tracker from bermuda, so that the shelly's can be used to track the room presence

**Describe alternatives you've considered**
I could remove the central tracker and use the shelly's as a proxy for the plantsensors. I however do not have plugs in all the rooms. So some sensors would become unavailable

**Comment by jleinenbach** [comment]
I agree, which is why I initiated a calibration feature request. Excluding a scanner/proxy is the worst-case scenario. I have BLE proxies placed behind furniture or under a table, resulting in a much weaker signal. Additionally, a BLE proxy located on the floor above, despite a concrete ceiling, sometimes receives a stronger signal than the BLE proxy in the same room as the device below.

**Comment by jleinenbach** [comment]
I guess this feature request is already planned:
https://github.com/agittins/bermuda/issues/45

**Comment by Sceptorrh** [comment]
Ah, Allright! I will close this ticket then

**Comment by agittins** [comment]
Duplicate of #45
