### ISSUE TITLE
Feature request: Battery level sensors and Alert buttons on devices

### ISSUE THREAD

**Issue by Rembock** [agittins/bermuda#263]
**Is your feature request related to a problem? Please describe.**
I've just set up a keyfinder in Bermuda and just realised it isn't possible to read out the battery level or sending an alert.

**Describe the solution you'd like**
It would be nice to use the sensor and button so i can set up an notification in Home Assistant to change the battery on time or let the keyfinder beep when i lost it (again).

**Describe alternatives you've considered**
Adding the keyfinder to al my ESPHome based bluetooth proxies and configure the sensor and button from there, but that would be cumbersome because i need to do that for every new device.

**Additional context**
This integration is awesome! It's already pairing nicely with my mmwave and infrared sensors :)

**Comment by agittins** [comment]
Hmm, interesting question.

This might be outside of the scope of Bermuda, since really it's about passively listening for devices and having a go at working out where they are. Monitoring battery levels etc might be better suited to integrations that are tailored to individual devices, the way that BTHome or other per-device integrations work (they'll all work hapilly together in HA).

How is it sending the battery and/or button status? If you have NRFConnect you might send screenshots from that, the "raw" and "more info" screens in particular are useful. If the device requires a connection to get the battery state that would definitely be outside of Bermuda's scope, as I'd rather keep it "listen only" as far as possible, unless it's to address a core feature.

I'm glad you're finding it a good fit with your PIR and mmw sensors! I think it's definitely most powerful when combined like that :)

**Comment by jleinenbach** [comment]
IDK, my eufy SmartTrack Card has a UUID 6aa5000a-6352-4d57-a7b4-003a416fbb0b for the "Battery Level", but nothing for the button. But as expected, to get that information, nRFConnect activly connects to the device and discovers the services.

Considering the scope, I find it more useful to focus less on checking the buttons of the device and more on activating the tracker to play the find melody, even if this also requires an active connection.

For instance, the Android app "AirGuard" can make my SmartTrack card play a sound, presumably using an Apple standard. Although nRFConnect shows a "Find My Network Service" I am not sure how it plays a sound.

Given the scope of the app, monitoring the battery status seems quite interesting because if we have the tracker and the button, we already know where the tracker is.

However, I understand that there are likely other priorities before implementing such features.

**Comment by tbrasser** [comment]
I think you need to go here: https://github.com/bropat/eufy-security-client

**Comment by jleinenbach** [comment]
> I think you need to go here: https://github.com/bropat/eufy-security-client

This integration is not for Eufy trackers.

**Comment by tbrasser** [comment]
https://bropat.github.io/eufy-security-client/#/supported_devices

**Comment by agittins** [comment]
Thanks for the extra info. I do think that this is outside the scope of Bermuda, certainly for the currently intended milestones.

Bermuda is really about taking *any* advertising bluetooth device, and trying to derive its location. For any device-specific things (outside of actually just identifying that device), one needs to look for an integration specifically aimed at working with that device. Such integrations are typically not too hard to find in (or get into) core, since they have a straight-foward, well-defined role.

I'm going to close this as not-planned, but feel free to share any links to suitable integrations in here if it helps others out.
