### ISSUE TITLE
Support for Google tags (Moto Tag)

### ISSUE THREAD

**Issue by Stormblade** [agittins/bermuda#271]
I have just got a new Moto Tag for the Google Find my device network.
Is it possible to track these using bermuda?

It appears in  nRF Connect as an Eddystone device, with an unknown (0x40) frame type.
But its MAC address doesn't appear in bermudas list of devices.

Thanks.

**Comment by agittins** [comment]
I hope so. I don't have one yet, and the last time i tried to look up the protocol stuff my brain faded before i got anywhere 😅

If you can share screenshots from nrfconnect and a download diagnostics from Bermuda I can see if we can get it sorted.

**Comment by Stormblade** [comment]
Download diagnostics and screenshot attached.

[config_entry-bermuda-c0750e9d3f9a12237685b6e9ada90f58.json](https://github.com/user-attachments/files/16458704/config_entry-bermuda-c0750e9d3f9a12237685b6e9ada90f58.json)
![Screenshot_20240801_142054_nRF Connect](https://github.com/user-attachments/assets/56f4e2a0-50fc-4b87-bd4e-f47677562ea0)

**Comment by Stormblade** [comment]
Note, the "Data:" value has changed since that screenshot was taken, but the MAC address hasn't yet.

**Comment by agittins** [comment]
Great, thanks for the extra info. I took a bit of a look at the google find my device spec, and yeah the eddystone-with-frame-type-0x40 is a FMDN (Find My Device Network) advertisement (FYI, type-0x41 is a FMDN advert in "anti-tracking privacy" mode).

I am super hopeful that someone is (going to be) working on an FMDN integration. There are a couple of threads around, mostly old, and some being shot down with short-sighted "why would anyone want this" responses (god those shit me), but I haven't seen anything being actively worked on - hopefully now that there are actual devices out in the wild something will happen.

## Right now...

In the short term, from Bermuda's perspective, direct support of these is "out of scope", because I can't do anything to uniquely identify each tag in a passive way.

## Ideally...

For proper support, I'd love to see an FMDN integration in HA, which allows you to fast-pair your HA instance with tags/beacons, so that HA installs an "application ID" into the tag, which allows HA to identify the tag by its broadcasts. From there, I would certainly tie in with that integration so that Bermuda would automatically present those devices for tracking (just like it does for devices in the "Private Bluetooth Device" integration). For that matter, FMDN devices also have to support "Fast Pairing", and fast-pair devices are strongly "recommended" to use "resolvable public addresses", ie, IRK, ie, they could show up in Private Bluetooth Device, if we have a mechanism to derive the key - which is a bit trickier.

## Someday before then, perhaps...

As a secondary solution, I have been considering what I think of as "class-based tracking". Where Bermuda would see any class of device (say, an FMDN tag, or an apple AirTag etc) and track them as semi-anonymous devices. So that if a tag appeared, Bermuda would assign it to say "Anonymous FMDN Tag #1". You could never be sure that the tag showing as `#5` is or is not the new address of tag `#1`, but you could at least see how many tags of a given type are in your house right now, and where they are. I think that could be somewhat useful to folk (even as an anti-stalking feature it could be helpful).

From there we can make a best-effort of maintaining some continuity, so if one tag stopped advertising at just about the same time that a new address starting advertising, we could assume that it's just the new address for the old tag. Of course, when they leave the house you have no way of knowing which one returns, but it's *something*.

I've raised #272 to track this as a long-term feature request, and for now I'll close this one specifically, since I can't offer direct google tag support until an integration is done to handle the protocol parts.

**Comment by smaeul** [comment]
> For proper support, I'd love to see an FMDN integration in HA, which allows you to fast-pair your HA instance with tags/beacons, so that HA installs an "application ID" into the tag, which allows HA to identify the tag by its broadcasts.

FWIW, I've made some progress on this, discussion here: https://github.com/agittins/bermuda/discussions/747
