### ISSUE TITLE
Amendment to Supported Devices page in the Wiki

### ISSUE THREAD

**Issue by jackjourneyman** [agittins/bermuda#304]
Sorry if this is not the right place...

The "Supported Devices" page in the Wiki includes Android phones under "devices using IRK". I don't think there is any user access to the IRK of an Android device. For practical purposes the only option is to set up an iBeacon - I imagine most Home Assistant users would do this in the companion app (or the HA Wear OS app for watches).

Is it possible to submit edits to the Wiki?

**Comment by agittins** [comment]
Howdy! Thanks for prodding me into action on this! 😀 

There are definitely ways to get IRK from Android so the wiki isn't incorrect, but certainly incomplete. Quite a few users are using IRK with Androids, myself included.

I've updated the wiki with the methods I'm aware of, and I have plans to create an easier way that's more integrated with ESPHome / HA in the future.

The main method I prefer currently is to use https://github.com/fryefryefrye/Decoding-Random-Bluetooth-Address but it does require doing a one-off flash of an esp32 and connecting via serial to see the results.

FWIW I think the method of getting the iPhone IRK by digging around the insides of a macbook will also work with an Android that has been paired with it. But that doesn't help those of us without a macbook handy!

> Is it possible to submit edits to the Wiki?

Huh. I had assumed it would be, but it appears there isn't a straightforward way. I guess that's why projects usually end up putting their docs either in the repo or in a separate repo. I expect I'll end up doing the same at some point :-/

I'll mark this as closed for now, but feel free to add further comments etc if you find new info or run into problems.

**Comment by kennyMC** [comment]
Hi,
is it also possible to get the irk from an android wear device, like the samsung galaxy watch 7? I did the enroll method from espresence for my phone. Unfortunately this doesn't work with wearos because espresense cannot be selected for connection

**Comment by jackjourneyman** [comment]
Well...

When I said "user access" I kind of meant methods that don't involve a soldering iron... ;)

I've used the iBeacon approach with both an Android phone and with Wear OS. Both work, but both have long "unknown" gaps, in spite of not being included in battery saving etc. To be honest, I've given up on the phone and now have a tag attached to it - Tile do one the size and shape of a credit card, which fits nicely into the case.
