### ISSUE TITLE
After working several minutes, stopped working and area sensor remains unknown

### ISSUE THREAD

**Issue by guidotillema** [agittins/bermuda#312]
## Version of the custom_component

0.6.9rc2

## Configuration

[config_entry-bermuda-01J91ZM18SBPBGDMNHFMGCA62F-2.json](https://github.com/user-attachments/files/17194549/config_entry-bermuda-01J91ZM18SBPBGDMNHFMGCA62F-2.json)

## Describe the bug

I have 4 Esphome Bluetooth proxies set-up, and have added my iPhone, Watch and iPad to the Private BLE Device. Everything worked perfectly, but suddenly it stopped working and all devices reported unknown. I tried downloading the latest beta version, as I read this would resolve the problem, but no luck. I tried manually restarting and re-installing the application, but also no luck. The only thing that worked (several minutes) was deleting the Private BLE Device and re-inserting the IRK code.

**Comment by agittins** [comment]
Hi Guido, thanks for your report - and especially for including the diagnostics, that's super helpful.

This might be an issue related to the fact that you have *only* private ble devices set up, and Bermuda might be failing to get updates at a certain point, but it could possibly be an issue with the Private BLE Device integration.

Overall your bluetooth backend looks healthy, plenty of devices showing up and the scanners look to be doing their jobs with fresh adverts being delivered into HA.

In the device screen where it shows all the sensors, there are two "device tracker" entries. One is from Bermuda and one comes directly from Private BLE Device. If the Private BLE Device tracker *also* says "unavailable" or "unknown", then that will be the source of the problem, since Bermuda relies on Private BLE Device to find out what address the device is currently using. Here's a screenshot from my system to illustrate:
![image](https://github.com/user-attachments/assets/ab3db4a8-63bd-41cc-b720-92a73598c703)

If yours shows the Private BLE Device's `device_tracker` sensor to be working, but the Bermuda one says Unknown or unavailable then that would point to the issue being in Bermuda.

I'm running the same version of HA as you (2024.9.1) and haven't noticed a similar issue, but every system is a bit different...

What do your device tracker sensors look like currently? You could also use the "History" view and choose "add device" to add one of your tracked devices, which might give some useful info on what changed over time.

**Comment by guidotillema** [comment]
Thank you for your extensive reply, this is really appreciated and extremely helpful. :)

So I looked at your example, and I expect the problem might be on settings that I changed. I tried to clean up my entities, so I disabled the diagnostics for the device_tracker sensors, as I assumed that Home/Away was not used by the tracker, and only the Area and distance sensor were used. 

After re-enabling these entities, and restarting the Bermuda and Private BLE, all worked as expected again. If it is correct that these device_tracker entities are necessary for the integration to work, that that would have been the root cause of the problem. However, if not, then it might indeed be that this is caused by for example only Private BLE devices.

**Comment by agittins** [comment]
Ah that's interesting! I suspect that it was Private BLE Device's sensor that did it - Bermuda relies on Private BLE Device updating, and if it's sensor was disabled maybe it doesn't bother doing any updating. Well done connecting the dots!

I'll close this as fixed for now based on that, but feel free to reopen if it doesn't cover the issue. Cheers!
