### ISSUE TITLE
Lockup due to excessive HaBaseScanner records [was: cannot setup bermuda integration]

### ISSUE THREAD

**Issue by collateral87** [agittins/bermuda#317]
Unfortunately, I can't set up the integration. As soon as I add it, my Home Assistant system completely crashes. I can force a restart using "core restart" via SSH, and then I see that the integration wasn't set up.

I wasn't able to provide any logs or configuration.

I'm running HassOS in a VM on my Unraid server, and I have a few Atom Bluetooth devices set up via ESPHome. However, these are not yet assigned to any rooms.

v0.6.9rc2 is my version of bermuda
running homeassistant 2024.10.1

I'm a bit afraid to try the setup again, but I would like to provide you with the data. Can you tell me exactly what you need?

**Comment by agittins** [comment]
Yikes!

In the ssh connection, you could try `ha core logs` to see if that shows anything that might be helpful, but it might not.

I'm out of town currently and have fairly limited internet. I haven't tested HA 2024.10.1 myself yet, so it's *possible* that bermdua has a compatability issue - but I haven't heard other reports of anything similar, so maybe it's related to initial installation.

Can you let me know which other integrations you have enabled in your HA? I think there's a "blueooth companion app for android" that might have an interoperability thing with Bermuda, but I don't know specifically yet.

Do you think that HA crashed (ie, the program ended and exited) or did it hang, possibly using all the cpu or churning memory? If the ssh connection was painfully slow or difficult to establish that might indicate hanging/churning rather than a crash. That doesn't make it OK, of course! Just helps a bit when diagnosing.

**Comment by collateral87** [comment]
Ok i will test and will post here what i get

![Screenshot_20241008_013625_Samsung Internet.jpg](https://github.com/user-attachments/assets/694006c8-5c52-455f-8d5b-30e10dccbe29)

**Comment by agittins** [comment]
The first thing to do is to assign an "Area" to each of your proxies. In the esphome integration, click the device, then the pencil in the top-right, and choose/create an area for it. This will get rid of all the messages about that in the logs.

The message about pruning 10k entries hints that you might have another integration that is creating a ridiculous number of bluetooth entries. Can you tell me what other integrations you have installed?

**Comment by collateral87** [comment]
Thank you for your reply.
I've assigned all my proxies to rooms and disabled all my bluetooth or ble related integrations, but still the same:
![image](https://github.com/user-attachments/assets/6a604f56-10cd-4517-bea7-7fa752b1724d)

My Integrations are:
- Govee BLE (official)
- Ikea Idaesen Desk (official)
- Gardena Bluetooth (official)
- Yale Bluetooth (official)
- LED BLE (official)
- Bluetooth (official)
- IBeacon (official)
- Xiaomi BLE (official)
- SwitchBot Bluetooth (official)
- INKBIRD (official)
- LEDnetWF BLE (inofficial)

Other related:
- Battery Notes (inofficial)
- Virtual Components (inofficial)
- local Tuya (inofficial)
- OpenEPaperlink (inofficial)
- Magic Areas (inofficial)
- BodyMiScale (inofficial)
- AVM FritzTools (official)
- MQTT (official)
- Glances (official)
- Shelly (official)
- UPnP Availability Sensor (inofficial)
- UPnP/IGD (official)
- Proximity (official)
- ESPHome (official)

Do you have any idea what else I could test?

**Comment by agittins** [comment]
Do you have a list of the bluetooth-related integrations that you've had on there previously?

Even after disabling other bluetooth integrations, I think their data might still remain behind, and that might be what's bogging down Bermuda (it still says it has 10 thousand bluetooth entries it's tracking - anything over a few hundred is suspiciously large).

Would it be possible for you to send me a file from your HA system? If you are on a supervised vm install, when you ssh in it's at ~/config/.storage/bluetooth.remote_scanners

This file is where HA saves out the list of bluetooth advertisements and devices so that when it restarts it comes up with a workable set of (slightly stale) data. My guess is that this file has become very large, and contains thousands of entries that a particular integration has stored there.

If you are able to send me this file, I can probably:
- work out which integration is causing this
- alter Bermuda to ignore or filter data coming from this integration so we don't bog down the whole system
- submit a but report to the integration doing it

Note though that the file contains the names and possibly IP addresses of your proxies, and also all of the bluetooth data floating around your home - so you might not want to post it publicly here.

You can zip it up and email it to me at ash@ajg.net.au or you can upload it securely to my nextcloud at https://cloud.ajg.net.au/index.php/s/JpeXDnZQGeXqqHB which is only visible to me.

Email is probably only reliable up to about 10MB, but the nexcloud should be good for a gig or two.

Another thing you can try is:
- stop homeassistant
- rename the file
- start homeassistant
 
This would cause HA to start up with an empty bluetooth cache, and might allow things to work properly. The downside is that it won't tell us what caused it, and it might just happen again if the guilty integration is fired up again (either immediately, or over time, depending). Note that renaming it while HA is running won't do anything, as HA will just re-save it when it exits.

If you need help working out how to do these, let me know what tool(s)/OS you are using to ssh into your HA, and I can give you the commands required.

Within the ssh session it would be something like:

`ls -alF config/.storage/bluetooth*` - this should list two files, the `bluetooth.passive_update_processor` file should be perhaps a few dozen kB, and the `bluetooth.remote_scanners` file should be far less than a MB, but I suspect yours might be close to or larger than that. Don't proceed beyond this if you don't get a file listing, it means one or more of my assumptions about your system is wrong.

`mv config/.storage/bluetooth.remote_scanners config/.storage/bluetooth.remote_scanners.bad` would rename the file, but only do this when HA itself isn't running.

After restarting HA, running the `ls` command above another time will show you if the file has been returned and if it's size has changed.

**Comment by agittins** [comment]
Hey @collateral87 , I'm planning on submitting an issue with Homeassistant about this, because the bluetooth backend is what's saving and restoring this huge file of bluetooth data.

Are you OK with me posting redacted screenshots of your `bluetooth.remote_scanners` file to the issue ? I'll blank out all the MAC addresses), but not upload the full file.

Are you OK with me sending your entire `bluetooth.remote_scanners` file that you sent me on to one of the core developers (not via a public link) if they request it so they can reproduce the issue? This file **does** have MAC addresses in it, which is why I'd only share it privately with a core dev.

If you can let me know if you're OK with that I'll raise the request and link to it here so you can follow progress if interested.

**Comment by collateral87** [comment]
I did what you said and now i could setup bermuda ble. 
Thank you very much for that and your help.

Yes, you can send the files to the core developer team. Iam fine with this :)

**Comment by agittins** [comment]
Fantastic, that's great to hear!
I have raised an issue with HA core, and bdraco has asked for the file, which I've sent to his dropbox account. Thanks for taking the time to gather that info and send it through, and very glad you got it all working!
https://github.com/home-assistant/core/issues/130432

**Comment by agittins** [comment]
bdraco has merged a fix for restoring stale data now, which is great and I expect is likely to show up in the next release (or soon, anyway). I've also raised a ticket at https://github.com/kvj/hass_Bluetooth_Proxy/issues/3 now that the issue has been properly identified.

I'm going to keep this open a little longer until I decide how to handle existing systems that have this issue.

**Comment by agittins** [comment]
Closing this now, as the patch for HA to not restore these stale adverts is now out, in 2024.11.3, and hass_Bluetooth_Proxy has also implemented a fix for the timestamp differences.

Thanks collateral87 for sticking with me on this and providing the debug info we needed to nail down the cause and fixes. 👍🏼
