### ISSUE TITLE
Frequent ‘Away’ Status for iPhone with ESP32 BLE Tracking Despite 300-Second Timeout

### ISSUE THREAD

**Issue by cuichaobaobao** [agittins/bermuda#323]
你好，我正在使用家庭助理中的四个ESP32设备通过BLE跟踪我的iPhone。超时设置为300秒。然而，如所附屏幕截图所示，尽管我的手机大多是“家”，但它经常长时间显示为“离开”，通常持续10分钟或更长时间，然后重新连接并再次显示“家”。这个问题影响了我的自动化的可靠性。以下是我的设备详细信息：	•	手机型号：iPhone	•	ESP32设备数量：4	•	超时：300秒屏幕截图显示了10月9日晚上到10月10日上午之间的状态变化。你能帮忙找出可能导致这个问题的原因吗？有没有办法提高BLE跟踪的稳定性？
![Uploading 截屏2024-10-10 11.30.53.png…]()

**Comment by agittins** [comment]
> [via google translate] Hello, I am tracking my iPhone via BLE using four ESP32 devices in Home Assistant. The timeout is set to 300 seconds. However, as shown in the attached screenshot, although my phone is mostly "Home", it often shows as "Away" for long periods of time, often lasting 10 minutes or more, before reconnecting and showing "Home" again. This issue is affecting the reliability of my automation. Here are my device details: • Phone Model: iPhone • Number of ESP32 Devices: 4 • Timeout: 300 seconds The screenshots show the state changes between the evening of October 9th and the morning of October 10th. Can you help identify what might be causing this issue? Is there a way to improve the stability of BLE tracking?

Hi, sorry for the slow response, I've been away with limited internet.

Could you attach the screenshot again? It hasn't uploaded. Possibly due to copy/paste between translation etc.

If you can also attach a "download diagnostics" that would help a lot as well.
![image](https://github.com/user-attachments/assets/81f72d51-3bce-413d-af31-41a02ee8e3fd)

**Comment by cuichaobaobao** [comment]
[config_entry-bermuda-01J6R0YEMAPKCXBHWHTCWS120R-2.json](https://github.com/user-attachments/files/17672997/config_entry-bermuda-01J6R0YEMAPKCXBHWHTCWS120R-2.json)

**Comment by agittins** [comment]
Hi, thanks for sending your diagnostics through.

Everything looks good from the Bermuda side. The diagnostics only shows me the last 30 seconds or so, but it shows that your proxies are working very well, with new data reported about every second for your "chaorengegedeiphone15ble" iPhone. Even the more distant proxies like "ci_wo" which is about 15m away, reports regular advertisements:

```
 "hist_interval": [
              2.456113014020957,
              0.811037317966111,
              1.6260748209897429,
              0.833038330078125,
              0.30301394197158515,
              1.6510759679367766,
              0.8030369490152225,
              1.6450756930280477,
              1.033047528937459,
              1.635075228055939
            ],
```

This shows it receives an advertisement about every second, which is good.

I think what might be happening is perhaps your phone sometimes just stops transmitting. I hear that this is common with iPhones, and it depends on the iOS power-saving if different apps get to keep transmitting all the time or not.

It seems that there are a lot of variables which affect whether the iPhone keeps transmitting. Some suggestions include:
- Use the HA companion app more often. If the app is used a lot, iOS is more likely to leave it running in the background.
- Enable location access for the HA companion app for "always".
- Perhaps install another app that also sends BLE advertisements, so that even if HA companion app stops sending, maybe the other app will. Because you are using IRK, *any* app that transmits will be seen by Bermuda.
- Turn off "Auto Toggle Visibility" (maybe it is in bluetooth settings? I am not sure - it might be a setting specific to the "Room Assistant" app or a COVID exposure app)

[This person](https://github.com/mKeRix/room-assistant/issues/1153#issuecomment-1193281288) found that using iOS 16 beta solved the issue for them, but later commenters did not.

This paragraph [from the espresense docs](https://espresense.com/beacons/apple) might be helpful:
> Note: Some iOS devices do not emit a beacon while the phone screen is off if there is not a reason for the device to broadcast a signal, consequently the device may not appear while the screen is off. Something like an iWatch, Universal Clipboard with Handoff enabled, or other services that require the phone to communicate regularly may resolve this issue as they require the subject iOS device to communicate while ‘sleeping’. In the case you do not have a bluetooth device like an iWatch, some people report that using background apps like iCloud Family Sharing, iCloud Photo Backup, or Room Assistant have convinced the device to communicate while ‘sleeping’. This issue is not universal, but it’s not clear why this occurs at this time and you may not experience this issue even if the device seemingly has no reason to communicate.


Your proxies, HA and Bermuda appear to be working properly, so I think the issue will be your iPhone choosing not to transmit at certain times. Hopefully the information above might help you solve it. Because there is currently nothing I can do in Bermuda to solve the problem, I will close this issue, but if you have further questions please feel free to re-open it. Likewise if I find any new information I'll add a comment here as well.
