### ISSUE TITLE
Use mobile app beacon monitor as BT proxy node

### ISSUE THREAD

**Issue by ScottG489** [agittins/bermuda#327]
**Is your feature request related to a problem? Please describe.**
Incorporate more devices that can act as nodes listening for your tracked devices.

**Describe the solution you'd like**
The HA companion mobile apps let you set up devices as a beacon monitors. It records nearby beacons and their range and is exposed as attributes on the sensor. More information can be found in the [companion docs](
https://companion.home-assistant.io/docs/core/sensors/?_highlight=beacon&_highlight=monitor#bluetooth-sensors).

It would be nice to use these beacon monitor sensors as nodes in addition to BT proxies. I have a bunch of tablets around the house so it would improve coverage.

**Additional context**
I'm not sure if there's other information that the ESPHome BT proxies provide other than an ID and range, so perhaps this won't work. It would be nice as well if other types of devices were supported such as ESPresense.

**Comment by agittins** [comment]
Hi Scott, thanks for the suggestion!

There is a single API that Bermuda uses for advertisements, which is the HomeAssistant Bluetooth backend. I don't plan to change that, since I feel it is the only sensible path to take, and provides a clean, complete and open interface for bluetooth traffic.

Any devices that perform the roles of an HaScanner should work with Bermuda. Things that I know of that do this currently are:
- the ESPHome integration
- the Shelly integration
- maybe the ruuvi integration (untested)
- the local bluetooth integration (as a local scanner, and also without proper timestamps)
- some other custom integrations, but possibly in incompatible ways.

To use the HA companion app, the project could implement a HaRemoteScanner feature in the app and the integration, which could then permit the companion app to perform proxy things - either advertisement forwarding alone (like Shelly does) or full two-way proxying like esphome offers. The magic words you'd want in a feature request for the companion app are probably along the lines of "Implement BaseHaRemoteScanner for bluetooth proxying", and implementing a "non-connectable" scanner would probably be possible, while a "connectable" scanner might be impossible, depending on the local android bluetooth API.

Note that the current companion app's beacon monitor only logs **iBeacon** advertisements.

Doing this work is far outside of the remit of the Bermuda project, though. But if it is implemented, I'd certainly work to make sure Bermuda could make use of it.

FYI, Bermuda uses the entire advertisement, plus the rssi measurement and timestamp from the proxy. It can sort of work without the advertisement body itself if required, but definitely needs the mac address, rssi and a way to determine a reasonable timestamp, at a minimum.

Since there is nothing in the Bermuda project to "do" at this stage, I'll close this as a wontfix/notplanned, but please feel free to reopen or submit a new issue if the HA companion app does implement the feature in future, or if you come across other integrations that feed data into the HA bluetooth backend but don't work properly in Bermuda.

**Comment by ScottG489** [comment]
Great, thanks for your detailed response. That all makes sense!

**Comment by tbrasser** [comment]
This might work:
 https://github.com/kvj/hass_Bluetooth_Proxy_Companion

Didn't try it myself yet though

**Comment by ScottG489** [comment]
Thanks! I might give it a shot.

I did a quick dive into the code and it looks like it [uses HaRemoteScanner](https://github.com/kvj/hass_Bluetooth_Proxy/blob/master/custom_components/companion_bt_proxy/scanner.py#L8). Does this look compatible to you @agittins?

**Comment by agittins** [comment]
Well.....

I am only aware of that integration's existence because some folk who found Bermuda to destroy their system performance had it installed previously. In theory, if it includes timestamps, it should be compatible.

But it's *possible* that it creates so many device entries in the bluetooth backend that it causes Bermuda to bog down the whole system (as in, 10's to hundreds of thousands of device entries). Or it could be that the entries it creates might be a reasonable number, but Bermuda is getting confused about them and applies them more than once - I honestly don't know. For that matter it might be completely unrelated.

I want to try it out at some point and see, so that we can make them compatible - I just haven't had time yet.
