### ISSUE TITLE
Deleting a device does not fully remove it

### ISSUE THREAD

**Issue by talormanda** [agittins/bermuda#340]
## Configuration

![image](https://github.com/user-attachments/assets/03c879a1-a869-4205-b872-2ace7e293d32)

## Describe the bug

I added a device, removed it, restarted. It still shows there are 2 devices, yet only one is configured. Visiting the device, all the sensors it created are still there, but marked "unavailable".

## Diagnostics

[config_entry-bermuda-01JB73J0XCQ8R4BN0JZ10J4B1A.json](https://github.com/user-attachments/files/17546497/config_entry-bermuda-01JB73J0XCQ8R4BN0JZ10J4B1A.json)

**Comment by agittins** [comment]
Yes, I think this is normal? Bermuda is no longer creating the device at start-up, but HA is restoring it when it starts up. After some period of time (minutes?) HA will decide that Bermuda is no longer creating those entities, and will let you delete them.

I am wondering though if maybe Bermuda should be deleting them... but I suspect not, since deleting/recreating a device is something one might want to do without having all the old history deleted in the process. Maybe there's a best-practice guide on that somewhere...

**Comment by talormanda** [comment]
> Yes, I think this is normal? Bermuda is no longer creating the device at start-up, but HA is restoring it when it starts up. After some period of time (minutes?) HA will decide that Bermuda is no longer creating those entities, and will let you delete them.
> 
> I am wondering though if maybe Bermuda should be deleting them... but I suspect not, since deleting/recreating a device is something one might want to do without having all the old history deleted in the process. Maybe there's a best-practice guide on that somewhere...

I figured it would at least remove the sensors it created, because when I go and look at the integration, it says there are "2" devices. And the one I deleted is still counted, when I believe it really shouldn't be.

**Comment by agittins** [comment]
I agree that it's not a great experience!

Does this not work for you? There's a hidden option on the device page (but they don't seem to expose it on the device *list* ui):
![image](https://github.com/user-attachments/assets/18663aa6-86f0-4609-b565-78804b464211)

**Comment by talormanda** [comment]
Mine didnt exactly look like that because it merged onto another device page. I had picked my switchbot curtain, so it merged bermuda sensors onto the switchbot ones. I can try cloning my VM and testing to see if that option pops up later tonight. (I just dont want to really delete / re-add over and over)

**Comment by agittins** [comment]
Multi-integration devices should still work, the delete option changes depending on which path you came to the device through:

![image](https://github.com/user-attachments/assets/1e14b014-e41a-4f2a-8280-4661e7faff6a)

The main problem I think is that this option is just not very visible, and if you don't know to look for it one would never find it, since you can delete other stuff like entities OK, except for the disabled ones... it's confusing.

Oh, also - if HA hasn't been restarted since the device was removed from Bermuda (or any other integration), it may not show the device as being *able* to be removed, and the delete option won't appear. It's doubly-frustrating!

**Comment by agittins** [comment]
Hi @talormanda, I've just released v0.7.1 of Bermuda, and it includes some significant improvements in handling scanners coming and going. During part of my testing I disabled ble scanning on an esphome, and when it rebooted the associated entities seemed to deactivate in the way one would expect.

Since I think we covered most of your original issue, plus perhaps some extra improved functionality in the latest release, I'll close this issue, but please feel free to re-open if you find anything going on in the same vein.

Thanks for your report and follow-up!

**Comment by talormanda** [comment]
Sounds good thanks.

**Comment by mycanaletto** [comment]
You can't delete sensor entities that you've already deleted. I've done quite a few tests, and there are a lot that are no longer useful...
![Image](https://github.com/user-attachments/assets/d02228f3-1e83-4b7f-ada8-41c27a0e52b0)

![Image](https://github.com/user-attachments/assets/9fbe2c83-c3d1-4d41-9788-0d8e01b9e245)
