### ISSUE TITLE
After installing Bermuda it doesn't show in the integrations. 

### ISSUE THREAD

**Issue by Mikede78** [agittins/bermuda#342]
## Diagnostics

In HA, Settings, Devices and Services, Bermuda, click the three-dots and choose "Download Diagnostics.
This will chug away for a bit then present you with a json file that you can upload here.

Attach your "Download Diagnostics" result by clicking the paperclip above:
![image](https://github.com/user-attachments/assets/7a3ce102-0b96-46c5-9289-e3253a6f2164)

If Bermuda has been running a long time (several days) the diagnostics might take a long time
to generate. You can try reloading Bermuda first (HA, Settings, Devices and Services, Bermuda,
three-dots-menu, Reload), then wait a few minutes, then try the download diagnostics.

**Comment by Mikede78** [comment]
I found a way to add it

**Comment by agittins** [comment]
Great! I assume that you had to go into Settings, Devices and Services, click "Add" and find Bermuda, after installing in HACS? That's the "official" way of doing it, but I also added an autodiscovery thing so that for a fair percentage of users they could skip that step and it would show up automatically - but it's not guaranteed.

If you followed someone's vid they probably skipped the adding step because it autodiscovered for them, but it won't for everyone.
