### ISSUE TITLE
[Rate-limit] Global visible device count [and others]

### ISSUE THREAD

**Issue by DavidAntonin** [agittins/bermuda#377]
What is the meaning of Global visible device count for normal use? It fills my logs very quickly. 
![global visible device count](https://github.com/user-attachments/assets/57338981-97d8-44ad-879d-8cc3ba0fb8ae)

**Comment by agittins** [comment]
Good point. That collection of sensors should probably be limited to 60 second updates.

The global device count is effectively the count of how many unique bluetooth MAC addresses the system has seen recently (where "recently" is not tightly defined, since we prune the list occasionally). It is useful as one of the general indicators of health / functioning of the bluetooth backend, since the HA bluetooth integration doesn't give much visibility into whether it's working at all.

You're right though, those updates are excessive, I'll tame them down in a coming release.

**Comment by iotola** [comment]
I excluded them from the logbook as they are very excessive, mine hits 700 in a few hours.
