### ISSUE TITLE
Manual scanner sensor

### ISSUE THREAD

**Issue by kdkavanagh** [agittins/bermuda#395]
Is there a way to manually add an RSSI sensor as a participant in the set of trackers known to bermuda?  I have a number of wall tablets set up with the HA companion app, with the app configured as an ibeacon monitor.  This creates an entity in hass for each tablet with attributes for each detected ble mac and the current estimated distance (which can presumably be used to back out the raw RSSI)?  Those attributes can then be extracted out into their own dedicated sensor entities in hass.

Hoping to find a way to leverage those entities alongside other esp32 ble trackers throughout my house

Possibly related to #193

**Comment by agittins** [comment]
Howdy! Thanks for your suggestion. If you take a look at #327 you'll get the overall picture. In short - it might work well if the HA Companion app chose to implement the HA standard HaBaseScanner in the app, then it *should* work automatically.

Hacking around converting entities into scanner data would be quite circuitous, and wouldn't be something I'd accept into Bermuda. Converting from the distance estimate back to rssi requires knowing the reference power and the attenuation used in the original equation, plus we would probably have to make some fairly inaccurate assumptions about the timestamps of the advertisements, plus if we don't have the full content of the advertisement it reduces other functionality, too.

The *other* app and custom integration mentioned in #193 and #327 may still be a possibility, as described.

I'll close this ticket since the other two already address the likely options, but feel free to raise any questions you might have after looking them over.
